# Generated by Django 5.2.1 on 2025-07-29 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rcapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_data",
            old_name="EMAIL",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="user_data",
            old_name="NAME",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="user_data",
            old_name="PASSWORD",
            new_name="password",
        ),
    ]
